# Generated by Django 4.1.6 on 2023-02-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_kullanici'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kullanici',
            new_name='User',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='maxPeople',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
