# Generated by Django 4.1.6 on 2023-02-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_user_email_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
