# Generated by Django 4.1.6 on 2023-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_remove_user_email_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='wert@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
    ]
