# Generated by Django 4.1.6 on 2023-02-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_user_email_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
