# Generated by Django 4.2 on 2023-04-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_rename_user_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boards.activity')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='boards.user2')),
            ],
        ),
    ]
