# Generated by Django 4.2 on 2023-04-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='activityId',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='userId',
            new_name='user',
        ),
    ]
