# Generated by Django 4.2 on 2023-04-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_rename_activityid_useractivity_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.activity'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.user2'),
        ),
    ]
