# Generated by Django 4.2 on 2023-04-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_useractivity_activity_alter_useractivity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.user2')),
            ],
        ),
    ]
