# Generated by Django 4.2 on 2023-04-29 16:26

import boards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_userphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='photo',
            field=models.ImageField(upload_to=boards.models.get_file_path),
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='boards.user2')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='boards.user2')),
            ],
        ),
    ]
