# Generated by Django 4.2 on 2023-05-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_alter_userfollowings_unique_together_and_more'),
        ('boards', '0016_alter_activity_description'),
    ]

    operations = [
    ]
